### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by Aktimoose** [SorkoPiko/CommentKarma#1]
this mod just rate limits you from the servers immediately upon opening your profile ​  ​  ​   ​   ​     frankly i should have expected this considering what the mod does but yeah it is just entirely unusable
![image](https://github.com/user-attachments/assets/ce1c5658-abd9-42b8-ab43-02df594f31e3)

**Comment by SorkoPiko** [comment]
yeah, that's why this hasn't been approved for the index yet. i'm working on a fix rn. disable it for now.

**Comment by SorkoPiko** [comment]
fixed in v1.1.0
